[tool.poetry]
name = "check-psa"
version = "0.1.0"
description = ""
authors = ["Andrea Reina <andrea@omnistream.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
